version: '2'

services: 

  backend:
    image: node:boron
    volumes:
      - ./backend/:/usr/src/app
      - backend_node_modules:/usr/src/app/node_modules
      - /usr/src/app/ts-node
    working_dir: /usr/src/app
    command: sh -c 'npm install; npm run dev'
    ports:
      - "3125:3125"
    depends_on:
      - database
    
  frontend:
    image: node:boron
    volumes:
      - ./frontend/:/usr/src/app
      - frontend_node_modules:/usr/src/app/node_modules
    working_dir: /usr/src/app
    command: sh -c 'npm install; npm start'
    ports:
      - "3000:3000"

  database:
    image: mysql:5
    volumes: 
      - upgraded_todo_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: upgraded_todo
    ports:
      - "3306:3306"

volumes:
  upgraded_todo_data:
  backend_node_modules:
  frontend_node_modules: