-- MySQL Script generated by MySQL Workbench
-- 11/27/16 18:51:27
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema upgraded_todo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema upgraded_todo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `upgraded_todo` DEFAULT CHARACTER SET utf8 ;
USE `upgraded_todo` ;

-- -----------------------------------------------------
-- Table `upgraded_todo`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `upgraded_todo`.`user` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `email` VARCHAR(90) NOT NULL,
  `password` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  UNIQUE INDEX `password_UNIQUE` (`password` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `upgraded_todo`.`task`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `upgraded_todo`.`task` (
  `id` BIGINT(8) UNSIGNED NOT NULL,
  `data` JSON NULL,
  `status` TINYINT(1) UNSIGNED NOT NULL COMMENT '0: Opened\n1: On-going\n2: On-hold\n3: Completed',
  `category_id` BIGINT(8) UNSIGNED NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `upgraded_todo`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `upgraded_todo`.`category` (
  `id` BIGINT(8) UNSIGNED NOT NULL,
  `name` VARCHAR(45) NULL,
  `parentId` INT NULL,
  `task_format` JSON NULL,
  `task_id` BIGINT(8) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_category_task1_idx` (`task_id` ASC),
  CONSTRAINT `fk_category_task1`
    FOREIGN KEY (`task_id`)
    REFERENCES `upgraded_todo`.`task` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `upgraded_todo`.`user_has_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `upgraded_todo`.`user_has_category` (
  `user_id` INT UNSIGNED NOT NULL,
  `category_id` BIGINT(8) UNSIGNED NOT NULL,
  PRIMARY KEY (`user_id`, `category_id`),
  INDEX `fk_user_has_category_category1_idx` (`category_id` ASC),
  INDEX `fk_user_has_category_user_idx` (`user_id` ASC),
  CONSTRAINT `fk_user_has_category_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `upgraded_todo`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_category_category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `upgraded_todo`.`category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
